### ISSUE TITLE
Unexpected end of JSON input on start script

### ISSUE THREAD

**Issue by jschuur** [PascalPixel/twitter-follower-curator-bot#3]
I did a fresh install and supplied it with Twitter API 2.0 credentials and now get this error when running `pnpm run start`

```
❯ pnpm run start                                                                                     13:41 Lise

> @ start /Users/joostschuur/Code/Misc/twitter-follower-curator-bot
> ts-node ./scripts/main.ts

Starting...
Starting cacheTwitterUsers("followers")...
Getting followers... x
Got 999 followers.
Getting followers... REDACTED
Got 1771 followers.
Done cacheTwitterUsers("followers")!
Starting cacheTwitterUsers("following")...
Getting following... x
Got 887 following.
Done cacheTwitterUsers("following")!
Starting diffTwitterUserCaches("followers")...
/Users/joostschuur/Code/Misc/twitter-follower-curator-bot/utils/diffTwitterUserCaches.ts:26
  const usersCurrent: UserV2[] = JSON.parse(mostRecentFileData);
                                      ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at diffTwitterUserCaches (/Users/joostschuur/Code/Misc/twitter-follower-curator-bot/utils/diffTwitterUserCaches.ts:26:39)
    at async main (/Users/joostschuur/Code/Misc/twitter-follower-curator-bot/scripts/main.ts:10:3)
```

The first time around it actually complained because no `cache` direcvory existed, so the above error only began when I manually created one in the project root dir.

```
[Error: ENOENT: no such file or directory, open '/Users/joostschuur/Code/Misc/twitter-follower-curator-bot/cache/followers-2023-02-06.json'] {
```

Ultimately, it did generate a `followers-2023-02-06.json` and `following-2023-02-06.json` fine with what seems like the right lists though.

**Comment by jschuur** [comment]
Obviously, we'll need to see how things shake out in terms of Twitter API access after this week first.

Nice to be able to do a quick export though.

**Comment by PascalPixel** [comment]
Added a try/catch that says you don't have a previous cache file if it can't find any 😄
